# Generated by Django 4.1 on 2022-09-13 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('Prijmeni', models.CharField(max_length=20, verbose_name='Přijemení')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('tel', models.IntegerField()),
                ('mesto', models.CharField(max_length=80, verbose_name='Město')),
                ('ulice', models.CharField(max_length=80)),
                ('PSC', models.IntegerField(verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Pojištěnec',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=180)),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.CreateModel(
            name='ZalozenaPojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.IntegerField(blank=True, null=True, verbose_name='Částka')),
                ('platnost_od', models.CharField(blank=True, max_length=80, null=True)),
                ('platnost_do', models.CharField(blank=True, max_length=80, null=True)),
                ('pojistenec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.pojistenec', verbose_name='Pojištěnec')),
                ('pojistka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.pojisteni', verbose_name='Pojištění')),
            ],
            options={
                'verbose_name': 'Založena pojistka',
                'verbose_name_plural': 'Založené pojištění',
            },
        ),
    ]
