# Generated by Django 4.1 on 2022-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_pojistenec_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalozenapojisteni',
            name='predment_pojisteni',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Předmět pojištění'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='Prijmeni',
            field=models.CharField(max_length=20, verbose_name='Přijmení'),
        ),
    ]
