# Generated by Django 4.1 on 2022-09-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_zalozenapojisteni_predment_pojisteni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zalozenapojisteni',
            old_name='predment_pojisteni',
            new_name='predmet_pojisteni',
        ),
    ]
